### ISSUE TITLE
VBoxManage not found when VirtualBox installed by Boxen

### ISSUE THREAD

**Issue by DanielWright** [boxen/puppet-docker#3]
Not sure this module is being maintained, but:

When the VirtualBox dependency is handled by [Boxen][1], it appears that `VBoxManage` isn't in the `$PATH` when the `docker::service` module attempts to create the machine:

```
Notice: /Stage[main]/Docker::Service/Exec[docker-machine create]/returns: Error with pre-create check: "VBoxManage not found. Make sure VirtualBox is installed and VBoxManage is in the path"
Error: /opt/boxen/homebrew/bin/docker-machine create --driver=virtualbox local returned 3 instead of one of [0]
```

`VBoxManage` is available in `/usr/local/bin`, and I was able to work around the failed dependency by symlinking to `/usr/bin`. I'm wondering if there's a more reliable and automated workaround.

Thanks!

[1]: https://github.com/boxen/puppet-virtualbox

**Comment by jacobbednarz** [comment]
Thanks for raising this! I don't get this locally but I've also recently switched to the new docker for mac app so that could be covering it up `¯\_(ツ)_/¯`. I'll take a peek at your pull request and see what we can do.
